spring:
    datasource:
        url: jdbc:mysql://45.134.1.104:3306/caoshangfei?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
    jpa:
        properties:
            hibernate:
                hbm2ddl.auto: validate
        show-sql: true
server:
    port: 80
logging:
    level:
        org.springframework: info


