spring:
    datasource:
        url: jdbc:mysql://192.168.2.133:3306/fuwo_xgt?characterEncoding=UTF-8&serverTimezone=Asia/Hong_Kong&useSSL=false&autoReconnect=true
        username: root
        password: 123456
    redis:
         host: 192.168.2.221
    rabbitmq:
         host: 192.168.2.12
    jpa:
        properties:
            hibernate:
                hbm2ddl.auto: validate
        show-sql: true
    thymeleaf:
        cache: false
    mail:
        username: system@fuwo.com
        password: REyWf@eru2
oss:
    domain : http://img.fuwo.com/
    image:
        bucket-name: fuwo-img
        bucket-access-key: LTAIsJFOVobiTGNE
        bucket-access-secret: xqYHtHDDkjDUIE9KX65OzVGAcMhtAZ
    file:
        bucket-name: fuwo-store
        bucket-access-key: LTAIxAbQcjGF9eq6
        bucket-access-secret: QdLG1bvofoBligl3Fgkhw2vfHETtOY
